name: notes_app
description: A notes and tasks app implementation
version: 1.0.0

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  uuid: ^4.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  collection: ^1.17.2
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  sembast: ^3.5.0+1
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0
  material_design_icons_flutter: ^6.0.0
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2
  palette_generator: ^0.3.3
  image_cropper: ^5.0.1
  share_plus: ^7.2.1
  tuple: ^2.0.0
  image: ^4.1.3
  flutter_quill: any
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/cloud_pattern.png
    - assets/images/banana_pattern.png
    - assets/images/snow_pattern.png
